### PR TITLE
add segfault handler for debugging

### PR DESCRIPTION
**Pull request by Griffan**
This PR aims to resolve segfault reported by multiple users in issue https://github.com/Griffan/VerifyBamID/issues/45
To better trace the error without exchanging testing dataset, I added this simple debugging mode to print backtrace at the crash site.

## Debugging Mode

If you encounter abnormal errors, e.g. "Segmentation fault", you can try to recompile the build under debugging mode:
```
cmake .. -DCMAKE_BUILD_TYPE=Debug
make
```
and then rerun your command line to locate the backtrace message, and then post it to issues page, for example:
```
Stack trace (most recent call last):
#6    Object "VerifyBamID", at 0x10ad9d822, in main + 466
#5    Object "VerifyBamID", at 0x10ad9b53d, in execute(int, char**) + 8509
#4    Object "VerifyBamID", at 0x10adc70c7, in ContaminationEstimator::OptimizeLLK(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 903
#3    Object "VerifyBamID", at 0x10adc9408, in ContaminationEstimator::OptimizeHeter(AmoebaMinimizer&) + 1560
#2    Object "libsystem_platform.dylib", at 0x7ff8182f0dfc, in _sigtramp + 28
#1    Object "VerifyBamID", at 0x10ad9e3ed, in backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 13
#0    Object "VerifyBamID", at 0x10ad9e456, in backward::SignalHandling::handleSignal(int, __siginfo*, void*) + 70
```

### CODE REVIEW

**Comment by yfarjoun** [comment]
Thanks @Griffan. Trying this out. will report back.

**Comment by Griffan** [comment]
Hi @yfarjoun, I have pushed the fix by bypassing these samples with uninformative GT or PL fields. Let me know if it finish the job successfully on your side. Thanks!

**Comment by yfarjoun** [comment]
it worked (in that it didn't explode..) I am missing many sites, due to the fact that they are multi-allelic. how did you pre process the 1KG vcfs, as they have lots of multiallelic sites as well?

**Comment by hyunminkang** [comment]
I would recommend any multi-allelic sites as verifyBamID is using biallelic variants. If the reference data is too big, you may decompose the VCF into bi-allelics first and filter variants by missingness.

**Pull request merged**
